component twospeed "Checks if spindle speed is within range";
pin in float speedIn "Current spindle speed from motion";
pin in float refSpeed "Minimum speed threshold";
pin out bit isOn "True if speedIn > refSpeed";
function _;
license "GPL";
;;
FUNCTION(_) {
    if (speedIn > refSpeed) {
        isOn = 1;		//Activate low-speed contactor
    } else {
        isOn = 0;		//Activate high-speed contactor
    }
}
